name: l2
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6
  - numpy
  - scipy
  - pytorch
  - nltk
  - gensim
  - faiss-gpu
  - matplotlib
  - pip:
    - -e git+https://github.com/pyliaorachel/paperscraper.git#egg=paperscraper
    - marisa-trie
    - jieba
    - opencc-python-reimplemented
